version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major-updates:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
