<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackAsTool>True</PackAsTool>
    <ToolCommandName>tql</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Argu" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransactionQL.Application\TransactionQL.Application.fsproj" />
    <ProjectReference Include="..\TransactionQL.Input\TransactionQL.Input.fsproj" />
    <ProjectReference Include="..\TransactionQL.Parser\TransactionQL.Parser.fsproj" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

</Project>