<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="tql.vim" />
    <None Include="tql.iss" />
    <Compile Include="build.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fake.Core.Target" />
    <PackageReference Include="Fake.DotNet.Cli" />
    <PackageReference Include="Fake.Installer.InnoSetup" />
    <PackageReference Include="Fake.IO.Zip" />
    <PackageReference Include="MSBuild.StructuredLogger" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

</Project>
