<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Interpretation.fs" />
    <Compile Include="AST.fs" />
    <Compile Include="QLParser.fs" />
    <Compile Include="QLInterpreter.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FParsec" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransactionQL.Shared\TransactionQL.Shared.fsproj" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

</Project>
