name: .NET Core

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          release_name="tql-${{ matrix.target }}"

          # Build everything
          dotnet publish TransactionQL.Console/TransactionQL.Console.fsproj -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "tql*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
