name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Get version number
        id: version
        shell: bash
        run: |
            version=`echo "${{ github.ref_name }}" | cut -c 2-`
            echo "Setting version to '$version'"
            echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Build
        run: >
            dotnet run
            --project ./src/TransactionQL.Build/TransactionQL.Build.fsproj
            -e parallel-jobs=4
            -e VERSION=${{ steps.version.outputs.VERSION }}

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "./ci/dist/*"
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
